class User{
    userId=0;
    firstName="";
    lastName="";
    address="";
    userType="";
    category="";
    email="";
    password="";
    constructor(userId,firstName,lastName,address,userType,category,email){
        this.userId=userId;
        this.firstName=firstName;
        this.lastName=lastName;
        this.address=address;
        this.userType=userType;
        this.category=category;
        this.email=email;
    }
}
module.exports=User;